### ISSUE TITLE
Why the expectation logs in falure situation has unexpected output?

### ISSUE THREAD

**Issue by havenqi** [cjstehno/ersatz#108]
It's good to see the details of the expectation logs. But I'm confused with expectation 0, and 1, because the test only has expecation 2 configured.
Could you explain more? Thanks.

![image](https://user-images.githubusercontent.com/11476671/47764984-ca63a080-dd02-11e8-8c53-84390e27b132.png)

```
def "Posting 1"() {
        setup:
        server.expectations {
            post('/posting') {
                body BODY_CONTENT, TEXT_PLAIN               // if BODY_CONTENT is used here, got '404: Not Found' due to failure of matching. Instead 'abc' works
                decoder TEXT_PLAIN, getUtf8String()

                responder {
                    body BODY_CONTENT                          // if BODY_CONTENT is used her, got bad response: 'Expectations (ErsatzRequest): <GET>, "BODY_CONTENT"'. Instead 'abc' works
                    encoder(TEXT_PLAIN, String) {
                        obj -> obj
                    }
                }
            }
        }.start()

        when:
        String value = exec(clientPost('/posting', 'text/plain; charset=utf-8', BODY_CONTENT).build()).body().string()

        then:
        value == BODY_CONTENT

    }
```

**Comment by cjstehno** [comment]
How are you configuring the `server` itself? Are you sure it is being cleaned up between tests? Something like:

```groovy
@AutoCleanup 
private final ErsatzServer ersatzServer = new ErsatzServer()
```

If not, this could cause the extra expectations, since they are not being cleaned out in a reused server.

**Comment by cjstehno** [comment]
Also, just FYI, calling `expectations` calls `start()` unless `autoStart false` is specified, so your explicit `start()` call is not needed.

**Comment by cjstehno** [comment]
Well, seeing the code in your other issue, it appears you are cleaning things up as you should, perhaps I broke something in the recent update. I will take a look. 

Thanks for reporting.

**Comment by cjstehno** [comment]
It appears that this is directly related to your other issue #107 - when the Groovy closure variable resolution gets confused it does some odd things. The response body DSL method calls the request body object in this case which creates another request expectation. I am going to close this issue and address both in the other ticket.
