### ISSUE TITLE
consider switching to uppercased method names in 2.x

### ISSUE THREAD

**Issue by musketyr** [cjstehno/ersatz#110]
using method `get` causes a problem within DSLs as it also allows to use unknown properties. instead of property missing exception, you get an expectation. consider naming the method `GET` instead and rename all the other methods to use uppercased characters.

**Comment by cjstehno** [comment]
Hmm. I actually don't use missing method or properties, it's all coded and the in 2.0 it's going to be written in pure Java. I'll consider the upper case method names but maybe as an option rather than the only way. Thanks.

**Comment by musketyr** [comment]
It doesn't actually matter whether it is intended or not. Any missing
property is translated into `get('propertyName')`. Even worse, as the
property resolution is currently broken, the properties present in spec
(except local variables) also resolved using the `get` method.

Dne út 20. lis 2018 18:15 uživatel Christopher J. Stehno <
notifications@github.com> napsal:

**Comment by cjstehno** [comment]
I guess I'm not fully understanding what you mean. I'll take a deeper look at this after this holiday week when my brain is back "on". 🦃

**Comment by cjstehno** [comment]
Ok, this all makes sense now. I'm not really a fan of the all-caps methods but I'll either deal with it or come up with something better. Thanks for pointing this out.

**Comment by cjstehno** [comment]
When I was coming up with the original design for the DSL I considered using a more generic approach for the request methods, something like:

```groovy
server.expectations {
    request(GET, '/foo'){
        // inside is similar to existing...
    }
    request(HEAD, '/bar'){
        // ...
    }
}
```

It still has a nice, expressive look to it and it would reduce the somewhat-duplicated methods in `Expectations` down to a couple. The `GET` in this case would be an enum with a value for each supported HTTP method type.

With the alternative being your suggestion of capitalized methods, such as:

```groovy
server.expectations {
    GET('/foo'){
        // inside is similar to existing...
    }
    HEAD('/bar'){
        // ...
    }
}
```

Syntactically, the two are not all that different, but I think I may lean towards the first approach mainly for its reduction of code.

What are your thoughts on this?

**Comment by KrzysztofKowalczyk** [comment]
I had problem with get(String) in my dsl. There is simple workaround for missing property resolution. 
Instead of 
```groovy
def get(String) {}
```
Use 
```groovy
def get(CharSequence) {}
```

This way the API stays the same, but it is not considered a missing property getter.

**Comment by cjstehno** [comment]
@KrzysztofKowalczyk Interesting, I will definitely look at that as an alternative to the uppercase names. Thanks.

**Comment by musketyr** [comment]
thanks @KrzysztofKowalczyk I'll check this in my DSLs as well

**Comment by cjstehno** [comment]
Ok, it took some time, but I am warming up to this change. I have added the all-caps methods in 1.10 with the old lower-case ones deprecated - to be removed in 2.0.
