### ISSUE TITLE
carry over the top level closure's owner

### ISSUE THREAD

**Issue by musketyr** [cjstehno/ersatz#111]
when there are nested closures as a part of the DSL the DSL users still expect the owner is the owner of the very first closure (the surrounding object) not the `n-1` closure.

feel free to use https://github.com/jasanspace/groovy-closure-support

I'm working on a series about Groovy Builders where I'm explaining this more thoroughly but it is not available yet.

**Comment by cjstehno** [comment]
I changed stuff in the last release to delegate first, which probably caused this issue. I'll read your suggestions since I've never run into a good solution for the scoping issue. Thanks.
