### ISSUE TITLE
Cookie Tesing Features

### ISSUE THREAD

**Issue by dwclark** [cjstehno/ersatz#44]
@cjstehno 

1) Ability to specify more than key/value for cookies. Especially path and expiration would be very handy.
2) Ability to assert that cookies are not present in a request. This may be possible already with Hamcrest matchers. If so, I would like to add them to the http-builder-ng tests.

**Comment by cjstehno** [comment]
Fair enough. I considered supporting more of the cookie features during my initial implementation, but got lazy about it.

I should be able to get these in over the weekend.

**Comment by dwclark** [comment]
Let me know when it drops, I'm planning on expaning the cookie tests when it happens.
