### ISSUE TITLE
Explore using in Kotlin

### ISSUE THREAD

**Issue by cjstehno** [cjstehno/ersatz#51]
Explore how Ersatz may be used from Kotlin. 

* Are there any issues with using it? If so, what can be done to resolve them?
* Document how it may be used in the User Guide

**Comment by musketyr** [comment]
Kotlin seems to be very friendly to closure + delegate DSLs. I think only thing we need to figure out is how to set _recipient_ from plain java in similar way how I'm doing this for Groovy: https://github.com/jasanspace/groovy-closure-support

**Comment by cjstehno** [comment]
As a starting point I have added a kotlin usage test and documented it in the user guide. It works in the basic sense - I can start adding helpful tweaks as needed (and probably as I get more into Kotlin :-))
