### ISSUE TITLE
Kotlin DSL

### ISSUE THREAD

**Issue by cjstehno** [cjstehno/ersatz#76]
Create an extension project to provide a Kotlin DSL - Kotlin works with the current Ersatz; however, it has to use the Java API. It would be nice to have a clean DSL for Kotlin.

Along those lines, consider pulling out the Java and Groovy DSLs into a separate extension and having the core be Java which is layered on with a DSL of choice... just something to consider while implementing this.

**Comment by musketyr** [comment]
please, let me know if you find out some nice way how to incorporate Kotlin :-) I wonder if there is possible something similar I'm doing with https://github.com/jasanspace/groovy-closure-support

**Comment by cjstehno** [comment]
I have two current thoughts:

1. Create a separate project providing a Kotlin extension to Ersatz - this would require some refactoring to isolate the configuration from the server a bit more (probably a good thing anyway).
2. A major refactoring of the project splitting it into four projects: core, java, groovy and kotlin. This approach seems cleanest to me since it provides the core as a library that the various DSLs just configure and use. This would obviously be a more aggressive release; however, other than changing some dependency names the interface to the user should not change.

I hope to start on one or the other of these once I get bored with my Rust experimentation. :-)

**Comment by cjstehno** [comment]
I wrote up a small demo project (https://github.com/cjstehno/polyglot) which uses a Kotlin-based project to provide a nice DSL-style interface for Kotlin, Java and Groovy with little fuss... this may lead to re-writing Ersatz in Kotlin.

**Comment by musketyr** [comment]
I've also tried to add Kotlin DSL to spreadsheet builder but I've faced
problem with SAM types being resolved instead of functional declaration in
extension methods. Maybe you're having same problem. I got an idea that the
functional interface I'm using might have to be written in Kotlin but
haven't get any further.

https://discuss.kotlinlang.org/t/overloading-using-extension-method/4990

Dne út 31. 10. 2017 19:42 uživatel Christopher J. Stehno <
notifications@github.com> napsal:

**Comment by cjstehno** [comment]
Another interesting link 

https://github.com/gradle/kotlin-dsl/blob/6a3c51a65e8423aa33432b816996360cd32e7906/provider/src/main/kotlin/org/gradle/kotlin/dsl/GroovyInteroperability.kt

The Gradle Kotlin DSL provides a means of creating delegating Groovy closures in Kotlin. I have not played with this yet, but it seems promising.

**Comment by cjstehno** [comment]
Being that this is a testing library and that I intend (and promote) using Groovy/Spock for testing at this point, even when coding in Kotlin, I am going to close this task.
