### ISSUE TITLE
vanilla-core dependency missing

### ISSUE THREAD

**Issue by ironcamel** [cjstehno/ersatz#83]
I had a job that was working before and recently started failing with the following error:

```Error grabbing Grapes -- [unresolved dependency: com.stehno.vanilla#vanilla-core;0.5.1: not found]```

I checked the maven site: https://mvnrepository.com/artifact/com.stehno.ersatz/ersatz/1.6.0

I noticed that the `vanilla-core` link is dead.  See the screenshot.  
![maven-ersatz-1 6 0](https://user-images.githubusercontent.com/50831/35241477-9810c538-ff84-11e7-9da9-0cb8f9136850.png)

Any ideas?

**Comment by cjstehno** [comment]
I think I fell prey to a bintray publishing bug. I will try to publish it again and let you know.

**Comment by cjstehno** [comment]
What version of Ersatz are you running? You could probably just exclude the vanilla dependency unless you are explicitly using it. I need to update the dependency since yes, 0.5.1 is dead (but probably still exists in my local repo)

**Comment by ironcamel** [comment]
I was using version 1.5.0 by including this line at the top of my test file:
```
@Grab('com.stehno.ersatz:ersatz:1.5.0')
```
I would be fine with switching to the latest, 1.6.0, but how do I exclude the vanilla dependency?

**Comment by cjstehno** [comment]
I am removing the vanilla dependency since it's a bit of a dead project... I will be releasing ersatz 1.6.1 shortly.

**Comment by cjstehno** [comment]
well, maven central is having issues right now, so as long as you are using bintray/jcenter you should be able to switch to eratz 1.6.1 and no longer have the dependency issue.

**Comment by ironcamel** [comment]
Thank you!
