### ISSUE TITLE
Chunked response support

### ISSUE THREAD

**Issue by radarsh** [cjstehno/ersatz#90]
Do you intend to provide support for mocking chunked responses similar to how [Wiremock does](http://wiremock.org/docs/simulating-faults/#chunked-dribble-delay)?

**Comment by cjstehno** [comment]
More information please.

I have multipart response support, if that's what you mean.

If not, please supply a detailed example. The link doesn't tell me anything.

**Comment by radarsh** [comment]
No, I'm not asking about multipart response support. I'm specifically asking about chunked Transfer Encoding. This is well explained in [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding#Chunked_encoding). In other words, this feature if implemented, would allow for the response to be chunked up and sent in several pieces (stream) rather than one monolithic unit.

Wiremock's `withChunkedDribbleDelay` allows us to simulate slow network connections by introduce a delay before each chunk is sent out.

[Wikipedia](https://en.wikipedia.org/wiki/Chunked_transfer_encoding) also does a good job at explain this.

**Comment by cjstehno** [comment]
I'll see what I can do. It may be a few months though as I have other higher priorities right now.

**Comment by cjstehno** [comment]
Figured out how to make this work with the existing architecture. It will be in 1.8.

**Comment by cjstehno** [comment]
This has been implemented in 1.8.1 which was released today.
